language: go node_js
sudo: enable

node_js:
  - 10

branches:
  only:
  - master
  - stable

install:
- wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
- sudo dpkg -i hugo*.deb

script:
  - sudo hugo
  - npm install hugo-algolia
  #- hugo-algolia -s

before_deploy:
  #- cd ./public

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "${Firebase_token}"

notifications:
  email:
    on_success: always
