language: go
sudo: required

install:
- wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- cd ./ublic

script:
  - hugo --cleanDestinationDir

deploy:
  provider: firebase
  token:
    secure: "${Firebase_token}"
