language: go
sudo: enable

install:
- wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
- sudo dpkg -i hugo*.deb

script:
  - sudo hugo

before_deploy:
  #- cd ./public

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "${Firebase_token}"

notifications:
  slack:
    on_success: always